version: '3.8'

services:
  code_interpreter:
    build:
      context: ./services/code-interpreter
      dockerfile: Dockerfile
    container_name: code_interpreter
    ports:
      - "8700:8700"
    environment:
      - CODE_API_KEY=your-code-api-key-here
      - PORT=8700
    volumes:
      - ./services/code-interpreter/data:/tmp/code-exec
    restart: always

  api:
    environment:
      - LIBRECHAT_CODE_API_KEY=your-code-api-key-here
      - CODE_BASEURL=http://code_interpreter:8700