services:
  mongodb:
    user: ""  # Remove user specification
  meilisearch:
    user: ""  # Remove user specification
  code_interpreter:
    build:
      context: ./services/code-interpreter
      dockerfile: Dockerfile
    container_name: code_interpreter
    ports:
      - "8700:8700"
    environment:
      - CODE_API_KEY=a1b2c3d4e5f67890123456789abcdef01234567890abcdef1234567890123456
      - PORT=8700
    volumes:
      - ./services/code-interpreter/data:/tmp/code-exec
    restart: always
  api:
    build: .
    environment:
      - LIBRECHAT_CODE_API_KEY=a1b2c3d4e5f67890123456789abcdef01234567890abcdef1234567890123456
      - LIBRECHAT_CODE_BASEURL=http://code_interpreter:8700
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - librechat_logs:/app/api/logs

  mcp-clickhouse:
    image: mcp-clickhouse:local
    container_name: mcp-clickhouse
    restart: always
    environment:
      CLICKHOUSE_HOST: "${CLICKHOUSE_HOST}"
      CLICKHOUSE_PORT: "${CLICKHOUSE_PORT}"
      CLICKHOUSE_USER: "${CLICKHOUSE_USER}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_SECURE: "true"
      CLICKHOUSE_VERIFY: "true"
      CLICKHOUSE_CONNECT_TIMEOUT: "30"
      CLICKHOUSE_SEND_RECEIVE_TIMEOUT: "30"
      CLICKHOUSE_MCP_SERVER_TRANSPORT: "http"
      CLICKHOUSE_MCP_BIND_HOST: "0.0.0.0"
      CLICKHOUSE_MCP_BIND_PORT: "3080"
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./librechat.yaml:/app/librechat.yaml
    ports:
      - "3081:3080"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
volumes:
  librechat_logs: